### ISSUE TITLE
OpenCV is not compatible with python-virtualenv

### ISSUE THREAD

**Issue by RobertKolner** [nikolaik/printermood#4]
This leads to a funny problem with multiple possible solutions:
- Install everything globally. Yuck.
- Decouple cam.py from everything else, use HTTP for communication between modules, run web server separately from the camera worker. A lot less yuck, but complicated.
- Dockerize. Probably the best compromise. Also allows us to use OpenCV and DLib at the same time with no installation quirks.

**Comment by nikolaik** [comment]
+1 dockerize

**Comment by nikolaik** [comment]
Decoupling makes a good step two, moving cam.py to a module running in it's own process with asyncio, tornado or twisted.

**Comment by nikolaik** [comment]
See #6

**Comment by RobertKolner** [comment]
Solved by #7.
